### ISSUE TITLE
Keyword Sections not properly populated during FGDC to ArcGIS upgrade

### ISSUE THREAD

**Issue by tbock** [USEPA/EPA-Metadata-Editor-5#2]
Keyword sections are not completely populated with their thesaurus content.  We are using tool provided with the EME 5 toolkit.  The workaround was to delete existing keyword sections and recreate them in ArcCatalog. 

![image](https://cloud.githubusercontent.com/assets/4040295/25912373/e59f8606-356b-11e7-9093-f179b5968741.png)

**Comment by torrin47** [comment]
Mind sharing an example doc where this behavior occurs and/or more detail on what doesn't survive the upgrade? In our testing this is working ok.
